export enum Action {
  LOGIN = 'LOGIN',

  PHONENUMBER_CHECK = 'PHONENUMBER_CHECK',

  EMAIL_CHECK = 'EMAIL_CHECK',

  PASSWORD_RESET = 'PASSWORD_RESET',

  DEVICE_CHECK = 'DEVICE_CHECK',

  TRANSACTION = 'TRANSACTION',
}
