package com.kotekka.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FailedAttemptHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFailedAttemptHistoryAllPropertiesEquals(FailedAttemptHistory expected, FailedAttemptHistory actual) {
        assertFailedAttemptHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertFailedAttemptHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFailedAttemptHistoryAllUpdatablePropertiesEquals(FailedAttemptHistory expected, FailedAttemptHistory actual) {
        assertFailedAttemptHistoryUpdatableFieldsEquals(expected, actual);
        assertFailedAttemptHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFailedAttemptHistoryAutoGeneratedPropertiesEquals(FailedAttemptHistory expected, FailedAttemptHistory actual) {
        assertThat(expected)
            .as("Verify FailedAttemptHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFailedAttemptHistoryUpdatableFieldsEquals(FailedAttemptHistory expected, FailedAttemptHistory actual) {
        assertThat(expected)
            .as("Verify FailedAttemptHistory relevant properties")
            .satisfies(e -> assertThat(e.getLogin()).as("check login").isEqualTo(actual.getLogin()))
            .satisfies(e -> assertThat(e.getIpAddress()).as("check ipAddress").isEqualTo(actual.getIpAddress()))
            .satisfies(e -> assertThat(e.getIsAfterLock()).as("check isAfterLock").isEqualTo(actual.getIsAfterLock()))
            .satisfies(e -> assertThat(e.getApp()).as("check app").isEqualTo(actual.getApp()))
            .satisfies(e -> assertThat(e.getAction()).as("check action").isEqualTo(actual.getAction()))
            .satisfies(e -> assertThat(e.getDevice()).as("check device").isEqualTo(actual.getDevice()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getReason()).as("check reason").isEqualTo(actual.getReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFailedAttemptHistoryUpdatableRelationshipsEquals(FailedAttemptHistory expected, FailedAttemptHistory actual) {
        // empty method
    }
}
