package com.kotekka.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserAccessAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAccessAllPropertiesEquals(UserAccess expected, UserAccess actual) {
        assertUserAccessAutoGeneratedPropertiesEquals(expected, actual);
        assertUserAccessAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAccessAllUpdatablePropertiesEquals(UserAccess expected, UserAccess actual) {
        assertUserAccessUpdatableFieldsEquals(expected, actual);
        assertUserAccessUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAccessAutoGeneratedPropertiesEquals(UserAccess expected, UserAccess actual) {
        assertThat(expected)
            .as("Verify UserAccess auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAccessUpdatableFieldsEquals(UserAccess expected, UserAccess actual) {
        assertThat(expected)
            .as("Verify UserAccess relevant properties")
            .satisfies(e -> assertThat(e.getLogin()).as("check login").isEqualTo(actual.getLogin()))
            .satisfies(e -> assertThat(e.getIpAddress()).as("check ipAddress").isEqualTo(actual.getIpAddress()))
            .satisfies(e -> assertThat(e.getDevice()).as("check device").isEqualTo(actual.getDevice()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAccessUpdatableRelationshipsEquals(UserAccess expected, UserAccess actual) {
        // empty method
    }
}
